apiVersion: v1
kind: Namespace
metadata:
  name: mcp-memory-stack
  labels:
    name: mcp-memory-stack
    environment: production
    team: platform
    app.kubernetes.io/name: mcp-memory-stack
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    kubernetes.io/description: "MCP Memory Stack microservices platform"
    contact: "platform-team@company.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-memory-stack-quota
  namespace: mcp-memory-stack
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    secrets: "20"
    configmaps: "20"
    services: "10"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-memory-stack-limits
  namespace: mcp-memory-stack
spec:
  limits:
    - default:
        cpu: "2"
        memory: "4Gi"
      defaultRequest:
        cpu: "200m"
        memory: "512Mi"
      type: Container
    - default:
        storage: "10Gi"
      type: PersistentVolumeClaim
