apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-embedding-service
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: microservice
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rust-embedding-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rust-embedding-service
        app.kubernetes.io/component: microservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        config/checksum: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
    spec:
      serviceAccountName: mcp-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: rust-embedding-service
          image: mcp/rust-embedding-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          env:
            - name: RUST_LOG
              value: "info"
            - name: RUST_BACKTRACE
              value: "1"
            - name: CONFIG_FILE
              value: "/app/config/config.toml"
            - name: API_KEYS
              valueFrom:
                secretKeyRef:
                  name: mcp-secrets
                  key: RUST_API_KEY
            - name: QDRANT_URL
              value: "http://qdrant-service:6333"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector:14268/api/traces"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: cache-volume
              mountPath: /app/cache
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30

      volumes:
        - name: config-volume
          configMap:
            name: mcp-config
            items:
              - key: rust-config.toml
                path: config.toml
        - name: cache-volume
          emptyDir:
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: rust-embedding-service
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: rust-embedding-service

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rust-embedding-service-hpa
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-embedding-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rust-embedding-service-pdb
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rust-embedding-service

---
# Service Monitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rust-embedding-service-monitor
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rust-embedding-service
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - mcp-memory-stack

---
# Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rust-embedding-service-network-policy
  namespace: mcp-memory-stack
  labels:
    app.kubernetes.io/name: rust-embedding-service
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rust-embedding-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow connections from fastify service
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: fastify-service
      ports:
        - protocol: TCP
          port: 8080
    # Allow connections from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    # Allow prometheus scraping
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9090
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow connections to Qdrant
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: qdrant
      ports:
        - protocol: TCP
          port: 6333
        - protocol: TCP
          port: 6334
    # Allow connections to Jaeger
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: jaeger
      ports:
        - protocol: TCP
          port: 14268
    # Allow HTTPS for external dependencies
    - to: []
      ports:
        - protocol: TCP
          port: 443
